CREATE TABLE [dbo].[USER] (
    [ID]          	INT           IDENTITY (1, 1) NOT NULL UNIQUE,
    [FISRT NAME]    VARCHAR (50)  NOT NULL,
    [LAST NAME]     VARCHAR (50)  NOT NULL,
    [EMAIL]         VARCHAR (255) NOT NULL UNIQUE,
    [PASSWORD]      VARCHAR (MAX) NOT NULL,
    [CELL NUMBER]   VARCHAR (10)  NOT NULL,
    [DATE OF BIRTH] DATE          NOT NULL,
    [GENDER]        VARCHAR (18)  NULL,
    [TYPE OF]       VARCHAR(10)   NOT NULL,
	[REGISTER DATE] DATETIME	  NOT NULL,
	[ISACTIVE]    	BIT           NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

CREATE TABLE [dbo].[BUSINESS] (
    [ID]          INT           IDENTITY (1, 1) NOT NULL UNIQUE,
    [OWNER ID]    INT  NOT NULL,
    [NAME]        VARCHAR (MAX) NOT NULL,
    [ADDRESS]      VARCHAR (MAX) NOT NULL,
    [IMAGE]       VARCHAR (MAX) NOT NULL,
    [DESCRIPTION] VARCHAR (MAX) NOT NULL,
    [ISACTIVE]    BIT           NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    FOREIGN KEY ([OWNER ID]) REFERENCES [dbo].[USER] ([ID])
);

CREATE TABLE [dbo].[CART] (
    [ID]                INT           IDENTITY (1, 1) NOT NULL UNIQUE,
	[USER ID]       	INT 		  NOT NULL,
    [PROD SUBTOTAL]     MONEY         NOT NULL,
	[SERVICES SUBTOTAL] MONEY         NOT NULL,
    [TAX]               MONEY         NOT NULL,
	[TOTAL]				MONEY         NOT NULL,
	[DISCOUNT]			MONEY         NOT NULL,
    [TOTAL PAID]        MONEY         NOT NULL,
    [BUSINESS ID]       INT 		  NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    FOREIGN KEY ([USER ID]) REFERENCES [dbo].[USER] ([ID])
);

CREATE TABLE [dbo].[INVOICE] (
    [ID]                INT           IDENTITY (1, 1) NOT NULL UNIQUE,
	[BUSINESS ID]       INT 		  NOT NULL,
	[USER ID]       	INT 		  NOT NULL,
    [PROD SUBTOTAL]     MONEY         NOT NULL,
    [TAX]               MONEY         NOT NULL,
    [SERVICES SUBTOTAL] MONEY         NOT NULL,
	[TOTAL]				MONEY         NOT NULL,
	[DISCOUNT]			MONEY         NOT NULL,
    [TOTAL PAID]        MONEY         NOT NULL,
    [DATE TIME]         DATETIME	  NOT NULL,
	[PAYMENT METHOD]	VARCHAR(MAX)	  NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    FOREIGN KEY ([USER ID]) REFERENCES [dbo].[USER] ([ID])
);

CREATE TABLE [dbo].[ORDERITEM] (
	[ID]                INT           IDENTITY (1, 1) NOT NULL UNIQUE,
	[INVOICE ID]		INT			  NOT NULL,
	[PRODUCT NAME]		MONEY		  NOT NULL,
	[PRODUCT QUANTITY]	MONEY		  NOT NULL,
	[PRODUCT PRICE]		MONEY		  NOT NULL,
	PRIMARY KEY CLUSTERED ([ID] ASC),
    FOREIGN KEY ([INVOICE ID]) REFERENCES [dbo].[INVOICE] ([ID])	
);

CREATE TABLE [dbo].[OPERATING HOURS] (
    [ID]          INT          IDENTITY (1, 1) NOT NULL UNIQUE,
    [BUSINESS ID] INT          NOT NULL,
	[DAY]         VARCHAR (11) NOT NULL,
    [OPEN TIME]   TIME (7)     NULL,
    [CLOSE TIME]  TIME (7)     NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    FOREIGN KEY ([BUSINESS ID]) REFERENCES [dbo].[BUSINESS] ([ID])
);

CREATE TABLE [dbo].[PRODUCT] (
    [ID]          INT           IDENTITY (1, 1) NOT NULL UNIQUE,
    [BUSINESS ID] INT           NOT NULL,
    [NAME]        VARCHAR (50)  NOT NULL,
    [DESCRIPTION] VARCHAR (MAX) NOT NULL,
    [PRICE]       MONEY         NOT NULL,
    [ALLERGIES]   VARCHAR (50)  NULL,
    [CATEGORY]    VARCHAR (50)  NOT NULL,
    [ISACTIVE]    BIT           NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    FOREIGN KEY ([BUSINESS ID]) REFERENCES [dbo].[BUSINESS] ([ID])
);

CREATE TABLE [dbo].[BRIDGE] (
    [CART ID]    INT   NOT NULL,
    [PRODUCT ID] INT   NOT NULL,
    [QUANTITY]   INT   NOT NULL,
    [PRICE]      MONEY NOT NULL,
    PRIMARY KEY CLUSTERED ([CART ID] ASC, [PRODUCT ID] ASC),
    FOREIGN KEY ([CART ID]) REFERENCES [dbo].[CART] ([ID]),
    FOREIGN KEY ([PRODUCT ID]) REFERENCES [dbo].[PRODUCT] ([ID])
);